### ISSUE TITLE
Key unique

### ISSUE THREAD

**Issue by Amulligue** [revlysJ/zipabox#1]
Petit message d'erreur quand j'essaye d'importer les modules de manière auto.

[MySQL] Error code : 23000 (1062). Duplicate entry '128-ZI_1_i_state' for key 'unique'

Serait-il possible de mettre la key unique sur l'uuid plutôt ?  =)

**Comment by revlysJ** [comment]
Je n'ai pas trop de temps pour l'instant à consacrer à ce plugin.
J'ai fait un petit correctif, dis moi si ça va mieux.

**Comment by Amulligue** [comment]
Top c'est niquel ;)

Pour actionner les prises chacon, qubino rail din et fibaro dimer, j'ai trouvé le réglage a faire dans la cmd action si tu veux :)

Telegram = @amulligue

**Comment by revlysJ** [comment]
Cool !
Je veux bien tes réglages, merci ;)

**Comment by Amulligue** [comment]
Ajoute moi à telegram, je te fais un screen :)

**Comment by revlysJ** [comment]
Oups, désolé, je n'avais pas vu ta réponse....
Je n'ai pas telegram, mais tu peux m'envoyer ça via le forum jeedom si tu veux.
