### ISSUE TITLE
[MySQL] Error code : 22001 (1406). Data too long for column 'name' at row 1

### ISSUE THREAD

**Issue by arlettazm** [revlysJ/zipabox#2]
Bonjour,
J'ai l'erreur [MySQL] Error code : 22001 (1406). Data too long for column 'name' at row 1
Lorsque j'essaye de faire l'import auto?
Que faire?
Merci

**Comment by revlysJ** [comment]
Bonjour,
Effectivement Jeedom demande un nom assez court pour ses commandes.
N'ayant plus la zipabox a disposition pour tester, je n'ai plus regardé le plugin depuis un moment.
Je viens de pousser un (petit) correctif qui est non testé donc.
Bonne soirée.

**Comment by arlettazm** [comment]
Bonsoir,
Merci, c'est bon pour l'import.
Bonne soirée
